images_dir: data/coco/train2017
annotations: data/coco/annotations/instances_train2017.json
val_images_dir: data/coco/val2017
val_annotations: data/coco/annotations/instances_val2017.json
out_dir: runs/exp1

epochs: 80
batch_size: 128
num_workers: 8
lr: 0.0004
image_size: 416
max_samples: null
val_max_samples: null
seed: 42
log_every: 20

base: 32
S: 13
C: null
